# Managed PostgreSQL with pgvector (docs/08 §6).
#
# One datastore rather than two. Postgres holds users, documents, chunk text,
# conversations, citations, jobs — and, since the pgvector work, the embedding
# index as well. That removes a second stateful service, its backups, and its
# failure mode, and puts the vector index under the same point-in-time
# recovery as everything else.

variable "identifier" { type = string }
variable "environment" { type = string }
variable "subnet_ids" { type = list(string) }
variable "security_group_ids" { type = list(string) }

variable "instance_class" {
  type    = string
  default = "db.t4g.micro"
}

resource "aws_db_subnet_group" "main" {
  name       = "${var.identifier}-subnets"
  subnet_ids = var.subnet_ids
}

resource "aws_db_instance" "main" {
  identifier     = var.identifier
  engine         = "postgres"
  engine_version = "17"
  instance_class = var.instance_class

  allocated_storage     = 20
  max_allocated_storage = 100
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = "lumora"
  username = "lumora"
  # Generated by RDS and written to Secrets Manager rather than passed in.
  # A password in a variable ends up in the state file, which is a file.
  manage_master_user_password = true

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = var.security_group_ids
  # No public endpoint. The API and worker reach it from inside the VPC.
  publicly_accessible = false

  # RPO ~5 minutes comes from PITR, not from the daily snapshot. Both are on;
  # the snapshot is what survives a deleted instance.
  backup_retention_period = 14
  backup_window           = "18:00-19:00"
  copy_tags_to_snapshot   = true

  # The two settings that decide whether a mistake is recoverable.
  deletion_protection       = var.environment == "production"
  skip_final_snapshot       = var.environment != "production"
  final_snapshot_identifier = var.environment == "production" ? "${var.identifier}-final" : null

  auto_minor_version_upgrade = true
  apply_immediately          = false

  performance_insights_enabled = true
  enabled_cloudwatch_logs_exports = ["postgresql"]

  tags = {
    Application = "lumora"
    Environment = var.environment
  }
}

# `CREATE EXTENSION vector` runs in migration 0008, not here — the extension is
# part of the schema and belongs with the migrations that depend on it. RDS
# ships pgvector as an available extension from PostgreSQL 15.2 onward; nothing
# needs enabling at the instance level.

output "endpoint" { value = aws_db_instance.main.endpoint }
output "master_secret_arn" { value = aws_db_instance.main.master_user_secret[0].secret_arn }
