import { createReadStream } from 'node:fs';
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, resolve, sep } from 'node:path';
import type { Readable } from 'node:stream';
import { logger } from '../../lib/logger.js';
import {
  StorageError,
  type PutOptions,
  type StorageProvider,
} from './storage-provider.interface.js';

/**
 * Bytes on local disk — the Phase 1 driver.
 *
 * Keys are generated by the application and are `{userId}/{uuid}{ext}`, so the
 * user's own directory falls out of the key rather than being computed here.
 * That layout keeps one user's files together, which makes an account deletion
 * a directory removal instead of a scan.
 *
 * The root is configured, never hardcoded. Nothing above this class knows a
 * filesystem exists.
 */
export class LocalStorageProvider implements StorageProvider {
  readonly name = 'local';

  private readonly root: string;

  constructor(root: string) {
    // Resolved once so every subsequent containment check compares two
    // absolute paths. A relative root would make `resolve` depend on the
    // process's working directory, which changes between `npm run dev` and a
    // systemd unit.
    this.root = resolve(root);
  }

  /**
   * Maps a key to an absolute path, and refuses anything that escapes the root.
   *
   * Keys are server-generated UUIDs, so in the current code path there is no
   * user input here at all — this is defence for the code that has not been
   * written yet. The day someone adds a key derived from a filename, or an
   * import path from a future connector, `../../etc/passwd` has to fail
   * loudly rather than resolve.
   *
   * Checks containment after resolution rather than pattern-matching for
   * `..`: encodings, symlinks, and mixed separators all defeat a substring
   * check, and none of them defeat comparing the resolved result.
   */
  private pathFor(key: string): string {
    if (key.length === 0 || isAbsolute(key) || key.includes('\0')) {
      throw new StorageError('put', key, new Error('Malformed storage key'));
    }

    const target = resolve(this.root, key);

    // The trailing separator matters: without it, a root of `/data/uploads`
    // would also accept `/data/uploads-evil`.
    if (target !== this.root && !target.startsWith(this.root + sep)) {
      throw new StorageError('put', key, new Error('Storage key escapes the root'));
    }

    return target;
  }

  async put(key: string, bytes: Buffer, _options: PutOptions): Promise<void> {
    const target = this.pathFor(key);

    try {
      await mkdir(dirname(target), { recursive: true });
      // `wx` fails if the object already exists. Keys are unique per upload,
      // so a collision means a bug or a replayed request — silently
      // overwriting would destroy another document's bytes while its row
      // still points at them.
      await writeFile(target, bytes, { flag: 'wx' });
    } catch (error) {
      logger.error({ err: error, key }, 'Storage put failed');
      throw new StorageError('put', key, error);
    }
  }

  get(key: string): Promise<Readable> {
    const target = this.pathFor(key);

    // The stream is returned unopened; a missing file surfaces as an `error`
    // event on it. Callers pipe it, so the failure reaches them either way,
    // and stat-ing first would be a TOCTOU check that proves nothing.
    return Promise.resolve(createReadStream(target));
  }

  async delete(key: string): Promise<void> {
    const target = this.pathFor(key);

    try {
      // `force` makes a missing file a success. Deletion runs after the row is
      // gone, so a retry must not fail on an object the first attempt already
      // removed.
      await rm(target, { force: true });
    } catch (error) {
      logger.error({ err: error, key }, 'Storage delete failed');
      throw new StorageError('delete', key, error);
    }
  }

  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Creates the root if it is missing, and proves it is writable.
   *
   * Called at boot. A misconfigured or read-only path otherwise surfaces on a
   * user's first upload, after they have waited for the bytes to transfer.
   */
  async verify(): Promise<void> {
    const probe = join(this.root, '.lumora-write-probe');

    await mkdir(this.root, { recursive: true });
    await writeFile(probe, 'ok');
    await rm(probe, { force: true });
  }
}
