import type { Readable } from 'node:stream';

/**
 * Byte storage, behind an interface (docs/05-rag-and-chat.md §2.1: "the
 * interface is `put/get/delete/exists` over a key, which is the common
 * denominator of every backend").
 *
 * **A key is opaque, not a path.** It is generated by the application, never
 * derived from a user-supplied filename, and a provider is free to interpret
 * it as a filesystem path, an S3 object key, or a database row. That framing
 * is what makes path traversal structurally impossible rather than something a
 * sanitizer has to catch: there is no user input in the address at all.
 *
 * The surface is deliberately small. Every method here exists on local disk,
 * S3, GCS, and Azure Blob; anything richer — directory listing, server-side
 * copy, signed URLs — would either force an emulation on some backend or leak
 * one backend's model into the application.
 *
 * `get` returns a stream rather than a Buffer. A 25 MB document held entirely
 * in memory is survivable; ten concurrent downloads of one is not, and the
 * parser in M4 consumes a stream anyway.
 */
export interface StorageProvider {
  /** Provider name, for logs and health reporting. */
  readonly name: string;

  /** Writes bytes at `key`, replacing anything already there. */
  put(key: string, bytes: Buffer, options: PutOptions): Promise<void>;

  get(key: string): Promise<Readable>;

  /**
   * Removes the object.
   *
   * **Idempotent**: deleting a key that is not there resolves rather than
   * throwing. Deletion runs after the database row is gone, so a retry must
   * not fail on an object the first attempt already removed — and a delete
   * that errors on "already absent" turns a successful cleanup into a stuck
   * job.
   */
  delete(key: string): Promise<void>;

  exists(key: string): Promise<boolean>;
}

export interface PutOptions {
  /**
   * Recorded by backends that carry object metadata, ignored by those that do
   * not. Never trusted on read — the stored type is the one the database
   * recorded after magic-byte sniffing.
   */
  contentType: string;
}

/**
 * Raised when the backend itself fails — a full disk, a refused connection, a
 * permissions error. Distinct from "the file is not acceptable", which is a
 * validation failure the caller can explain to a user.
 */
export class StorageError extends Error {
  constructor(
    readonly operation: 'put' | 'get' | 'delete' | 'exists',
    readonly key: string,
    cause?: unknown,
  ) {
    super(`Storage ${operation} failed`);
    this.name = 'StorageError';
    this.cause = cause;
  }
}
